### ISSUE TITLE
not work with kivymd-1.1.0.dev0

### ISSUE THREAD

**Issue by orcim** [kivymd-extensions/sweetalert#9]
### Description of the Bug

I tried the example of the repository but it doesn't work

### Versions

* OS:  Linux 5.4.0-125-generic #141-Ubuntu SMP
* Python: 3.8
* Kivy: 2.10
* KivyMD: 1.1.0.dev0

**Comment by HeaTTheatR** [comment]
@orcim Please, attach full log...

**Comment by orcim** [comment]
Sorry I was wrong repository, https://github.com/Kulothungan16/KivyMD-Project-Creator

**Comment by HeaTTheatR** [comment]
@orcim You didn't attach the log...

**Comment by orcim** [comment]
(envPy38_kivymd_110dev0) orcim@loris-G7-7700 ~/1work/_myTry/_inProgress/py-kiviMd/_envPy/KivyMD_Project_Creator $ python main.py 
[INFO   ] [Logger      ] Record log in /home/orcim/.kivy/logs/kivy_22-09-15_0.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
[INFO   ] [Python      ] Interpreter at "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 470.141.03'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce RTX 2060/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] 1.1.0.dev0, git-862171d, 2022-09-12 (installed at "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [KivyMD Project Creator] v0.5.0b
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event13
[INFO   ] [MTD         ] Read event from </dev/input/event13>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event13> range position X is 0 - 1349
[INFO   ] [MTD         ] </dev/input/event13> range position Y is 0 - 929
[INFO   ] [MTD         ] </dev/input/event13> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event13> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event13> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event13> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event13> rotation set to 0
[ERROR  ] [Image       ] Not found <assets/images/templates/.png>
[ERROR  ] [Image       ] Not found <assets/images/templates/.png>
[ERROR  ] [Image       ] Not found <assets/images/templates/.png>
[ERROR  ] [Image       ] Not found <assets/images/templates/.png>
[ERROR  ] [Image       ] Not found <assets/images/templates/.png>
[ERROR  ] [Image       ] Not found <assets/images/templates/.png>
 --- Logging error ---
 Traceback (most recent call last):
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 553, in execute_directives
     mod = importlib.__import__(package)
   File "<frozen importlib._bootstrap>", line 1093, in __import__
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd_extensions/sweetalert/__init__.py", line 1, in <module>
     from .sweetalert import SweetAlert
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd_extensions/sweetalert/sweetalert.py", line 62, in <module>
     from kivymd.utils.fitimage import FitImage
 ModuleNotFoundError: No module named 'kivymd.utils.fitimage'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 556, in execute_directives
     mod = importlib.__import__(module_name)
   File "<frozen importlib._bootstrap>", line 1093, in __import__
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd_extensions/sweetalert/__init__.py", line 1, in <module>
     from .sweetalert import SweetAlert
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd_extensions/sweetalert/sweetalert.py", line 62, in <module>
     from kivymd.utils.fitimage import FitImage
 ModuleNotFoundError: No module named 'kivymd.utils.fitimage'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
     msg = self.format(record)
   File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
     return fmt.format(record)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/logger.py", line 291, in format
     record = copy.deepcopy(record)
   File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
     y = _reconstruct(x, memo, *rv)
   File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
     state = deepcopy(state, memo)
   File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
     y = copier(x, memo)
   File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
     y[deepcopy(key, memo)] = deepcopy(value, memo)
   File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
     y = copier(x, memo)
   File "/usr/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
     y = [deepcopy(a, memo) for a in x]
   File "/usr/lib/python3.8/copy.py", line 210, in <listcomp>
     y = [deepcopy(a, memo) for a in x]
   File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
     rv = reductor(4)
 TypeError: cannot pickle 'traceback' object
 Call stack:
   File "main.py", line 90, in <module>
     MainApp().run()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 383, in idle
     self.dispatch_input()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd/uix/button/button.py", line 1068, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd/uix/behaviors/ripple_behavior.py", line 404, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "<string>", line 11, in <lambda>
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_git/01-Kulohungan16/KivyMD_Project_Creator/libs/uix/baseclass/templates_screen.py", line 23, in change_to_get_details
     utils.load_kv("get_details_screen.kv")
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_git/01-Kulohungan16/KivyMD_Project_Creator/libs/applibs/utils.py", line 10, in load_kv
     Builder.load_string(kv.read())
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/builder.py", line 372, in load_string
     parser = Parser(content=string, filename=fn)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 483, in __init__
     self.parse(content)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 590, in parse
     self.execute_directives()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 564, in execute_directives
     Logger.exception('')
 Message: ''
 Arguments: ()
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 553, in execute_directives
     mod = importlib.__import__(package)
   File "<frozen importlib._bootstrap>", line 1093, in __import__
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd_extensions/sweetalert/__init__.py", line 1, in <module>
     from .sweetalert import SweetAlert
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd_extensions/sweetalert/sweetalert.py", line 62, in <module>
     from kivymd.utils.fitimage import FitImage
 ModuleNotFoundError: No module named 'kivymd.utils.fitimage'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 556, in execute_directives
     mod = importlib.__import__(module_name)
   File "<frozen importlib._bootstrap>", line 1093, in __import__
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd_extensions/sweetalert/__init__.py", line 1, in <module>
     from .sweetalert import SweetAlert
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd_extensions/sweetalert/sweetalert.py", line 62, in <module>
     from kivymd.utils.fitimage import FitImage
 ModuleNotFoundError: No module named 'kivymd.utils.fitimage'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "main.py", line 90, in <module>
     MainApp().run()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 383, in idle
     self.dispatch_input()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd/uix/button/button.py", line 1068, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivymd/uix/behaviors/ripple_behavior.py", line 404, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "<string>", line 11, in <lambda>
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_git/01-Kulohungan16/KivyMD_Project_Creator/libs/uix/baseclass/templates_screen.py", line 23, in change_to_get_details
     utils.load_kv("get_details_screen.kv")
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_git/01-Kulohungan16/KivyMD_Project_Creator/libs/applibs/utils.py", line 10, in load_kv
     Builder.load_string(kv.read())
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/builder.py", line 372, in load_string
     parser = Parser(content=string, filename=fn)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 483, in __init__
     self.parse(content)
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 590, in parse
     self.execute_directives()
   File "/home/orcim/1work/_myTry/_inProgress/py-kiviMd/_envPy/envPy38_kivymd_110dev0/lib/python3.8/site-packages/kivy/lang/parser.py", line 565, in execute_directives
     raise ParserException(self, ln,
 kivy.lang.parser.ParserException: Parser: File "<inline>", line 4:
 ...
       2:#: import images_path kivymd.images_path
       3:#: import colors kivymd.color_definitions.colors
 >>    4:#: import SweetAlert kivymd_extensions.sweetalert.SweetAlert
       5:
       6:#: import TextFieldRound libs.uix.components.textfield.TextFieldRound
 ...
 Unable to import package 'kivymd_extensions.sweetalert.SweetAlert'
